### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by ralphhughes** [rainman74/NPPTextFX2#6]
Hi,

I've downloaded the DLL from the latest release and copied the file to "C:\Program Files\Notepad++\plugins" and restarted Notepad++
Still nothing under the plugins menu though, how do I install this please?

**Comment by TomasRiker** [comment]
For me, it worked by creating a new folder (I named it `NppTextFX`) inside the `plugins` directory and placing the DLL in there.

**Comment by TomasRiker** [comment]
I'm using the 32-bit version, so maybe there's a difference ...

**Comment by BloodShed-Oni** [comment]
The 64-bit version of the plugin doesn't load for some reason.

I tried the 32-bit version and it works.

**Comment by jaimelinharesjr** [comment]
For 64bits version:
Only rename the DLL NppTextFX64.dll to NppTextFX.dll
Work here.

**Comment by rainman74** [comment]
A Notepad++ plugin must always be located in a separate folder with the same name as the DLL, otherwise it will not be loaded.

Examples:

_\Notepad++\plugins\NppTextFX64\NppTextFX64.dll_ (64 bit version)
_\Notepad++\plugins\NppTextFX\NppTextFX.dll_ (32 bit version)
_\Notepad++\plugins\myFunnyPlugin123\myFunnyPlugin123.dll_

You can also rename the 64 bit plugin, then the folder name must be the same as for the 32 bit plugin.
